version: '3.5'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    tty: true
    restart: always
    volumes:
      - ./app:/src
    command: [sh, -c, npm install && npm run start]
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks: 
      - proxy-network  # プロキシネットワーク
      - app-network    # アプリネットワーク

# プロキシネットワーク、アプリネットワークと接続
networks:
  proxy-network:
    name: proxy_network
  app-network:
    name: app_network
